version: '3'

services:
  database:
    image: 'mongo'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=TRADER
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=root
    volumes:
      - ./init.js:/docker-entrypoint-initdb.db/init.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'

